package filechange

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGeneratedArtifactsDoNotReadSourceFilesAsBuildOutput(t *testing.T) {
	t.Parallel()
	require.True(t, generatedArtifact("/project/build/classes/Main.class"))
	require.False(t, generatedArtifact("/project/src/build/helpers.go"))
	require.False(t, generatedArtifact("/project/reference.jar"))
	root := visibleRestoreRoot(t)
	p := newProcessReview(root, nil)
	p.Begin("build", "compiler")
	record := p.executed(nil, []string{"compiler"})
	path := filepath.Join(root, "build", "Main.class")
	p.before(record, path)
	put(t, root, "build/Main.class", "generated bytes")
	review := p.End("build")
	require.Len(t, review.Changes, 1)
	require.Equal(t, "generated", review.Changes[0].Transfer.Kind)
	require.Empty(t, review.Changes[0].After.Content)
}
